FTA/FTA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from datetime import datetime
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
import django.contrib.auth.views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('<sport_slug>/', include('sports.urls')),

    #apis
    path('api/', include('articles.api.urls')),
    path('api/', include('teams.api.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    #path(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FTA/sports/urls.py
from django.conf.urls import url, include
from django.urls import path
#from sports.api.views import TeamAPIView
from . import views as sports_views
from django.views.generic import TemplateView

from sports.views import SportView, NationView

app_name = 'sports'

urlpatterns = [


    path('<slug:country_slug>/', NationView.as_view(), name='national-home'),
    path('', sports_views.SportView.as_view(), name='sport-home'),
    #url(r'^api_data/', include('sports.api.urls')),
    #url(r'^monthly-view/$', cricket.CricketCalendar.as_view(), name='monthly-view'),
    # path('<slug:country_slug>', sports_views.ListView.as_view(), name='national-home'), #unused
]

FTA/templates/submenu/competition.html
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Competition
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
    <ul>
      {% if country_slug == None %}
        {% for info in all_competition %}
            <li><a href="{% url sport_menu.sport_slug|add:':competition' info.country.country_slug info.competition_slug %}">
                  <img src="{{info.country.flag.url}}" alt="">
                  {{info.name}}
                </a></li>
        {% endfor %}
        {% else %}
      {% endif %}
      {% if path.contains == country_slug %}
        {% for comp in country_competition_info %}
            <li><a href="{% url sport_menu.sport_slug|add:':competition' comp.country.country_slug comp.competition_slug %}">
                  {{comp.name}}
                </a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>

FTA/templates/submenu/country.html
{% if country_selector %}
    <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Country
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <ul>
      {% for country in country_selector|dictsort:"name" %}
        <li>
          <a href="{% url 'sports:national-home' sport_menu.sport_slug country.country_slug %}">
          <img class="small_flag" src="" alt="">{{country}}
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</li>

{% endif %}