FTA/FTA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from datetime import datetime
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
import django.contrib.auth.views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('<sport_slug>/', include('sports.urls')),

    #apis
    path('api/', include('articles.api.urls')),
    path('api/', include('teams.api.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    #path(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FTA/articles/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import IndexView, SportNationView, DetailView
from sports.views import ListView
from django.views.generic import TemplateView

app_name = 'articles'

urlpatterns = [

    path('<slug:sport_slug>/<slug:post_slug>', DetailView.as_view(), name='detail'),
    path('', IndexView.as_view(), name='index'),


    #url(r'^monthly-view/$', cricket.CricketCalendar.as_view(), name='monthly-view'),
    #url(r'^(?P<category_slug>[-_\w]+)/$', sports_views.ListView.as_view(), name='sport-category'),
]

FTA/sports/urls.py
from django.conf.urls import url, include
from django.urls import path
#from sports.api.views import TeamAPIView
from . import views as sports_views
from django.views.generic import TemplateView

from sports.views import SportView, NationView

app_name = 'sports'

urlpatterns = [


    path('<slug:country_slug>/', NationView.as_view(), name='national-home'),
    path('', sports_views.SportView.as_view(), name='sport-home'),
    #url(r'^api_data/', include('sports.api.urls')),
    #url(r'^monthly-view/$', cricket.CricketCalendar.as_view(), name='monthly-view'),
    # path('<slug:country_slug>', sports_views.ListView.as_view(), name='national-home'), #unused
]

FTA/sports/models.py
from django.db import models

# Create your models here.


class Sport_Category(models.Model):
  name = models.CharField(max_length=100, db_index=True)
  category_slug = models.SlugField(max_length=100, db_index=True)

  def __str__(self):
    return self.name

# def get_absolute_url(self):
    # return reverse('sports:sport-category', kwargs={'slug':self.category_slug})


class Sport(models.Model):
  name = models.CharField(max_length=100, db_index=True)
  sport_slug = models.SlugField(max_length=100, db_index=True)
  category = models.ForeignKey('Sport_Category', on_delete=models.CASCADE,)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('sports:national-home', kwargs={'slug': self.sport_slug})

FTA/sports/views.py
from django.db.models.functions import Lower
from django.shortcuts import render, get_object_or_404
from articles.models import Post
from sports.models import Sport
from nations.models import Country_Data
from teams.models import Team
from django.views.generic.list import ListView

# Create your views here.


class SportView(ListView):
    template_name = "articles/index.html"
    context_object_name = 'sport_list'

    def get_context_data(self, **kwargs):
        context = super(SportView, self).get_context_data(**kwargs)
        context['sport_menu'] = get_object_or_404(Sport, sport_slug=self.kwargs['sport_slug'])
        context['country_selector'] = Country_Data.objects.filter(sport=self.sport).order_by('sport')
        return context

    def get_queryset(self):
        self.sport = get_object_or_404(Sport, sport_slug=self.kwargs['sport_slug'])
        return Post.objects.filter(post_category=self.sport)


class NationView(ListView):
    template_name = "articles/index.html"
    context_object_name = 'sport_list'

    def get_context_data(self, **kwargs):
        context = super(NationView, self).get_context_data(**kwargs)
        context['sport_menu'] = get_object_or_404(Sport, sport_slug=self.kwargs['sport_slug'])
        context['country_selector'] = Country_Data.objects.filter(sport=self.sport).order_by('sport')

        return context

    def get_queryset(self):
        self.sport = get_object_or_404(Sport, sport_slug=self.kwargs['sport_slug'])
        self.country = get_object_or_404(Country_Data, country_slug=self.kwargs['country_slug'])
        return Post.objects.filter(post_category=self.sport, country_slug=self.country)

#.distinct('nation',) might work?
# context['country_selector'] = Team.objects.filter(sport=self.sport).values_list('nation', flat=True).distinct() XXdoesnt workXX

FTA/sports/templates/sports/old/sport-home.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="carousel slide col-6" id="carouselExampleIndicators"  data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
        </ol>

        <div class="carousel-inner" role="listbox">

          {% for post in sport_list|slice:":5"%}
          {% if post.headline_image %}
          <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}" id="slide{{ forloop.counter }}">
            <a href="{% url 'articles:detail' post.post_category.sport_slug post.post_slug %}">
            <img class="d-block img-fluid" src="{{ post.headline_image.url }}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
              <h3>{{ post.title }}</h3>
              <p>{{ post.short_description }}</p>
            </div>
            </a>
          </div>
          {% endif %}
          {% endfor %}


        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        </div>
      </div>

      <div class="top-headline offset-2 col-4 mt-3">
        <div class="top-title d-flex justify-content-center"><h3 class="gold-text">Top Headlines</h3></div>
        {% for post in sport_list|slice:":5"%}
        {% if not post.headline_image %}
          <a href="{% url 'articles:detail' post.post_category.sport_slug post.post_slug %}">
            <h3>{{ post.title }}</h3>
          </a>
        {% endif %}
        {% endfor %}
        <div class="top-title d-flex justify-content-center mt-3"><h3 class="gold-text">Video News</h3></div>
        {% for video in sport_list %}
          {% if video.youtube_link %}
          <h5>{{video.title}} - <small><a href="{{video.get_absolute_url}}">Read More</a></small></h5>
          <iframe width="100%" height="100%" src="{{video.youtube_link}}" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
          <hr>
          {% endif %}
        {% endfor %}
      </div>
      </div>
    </div>


    <div class="row">
      {% for post in sport_list|slice:"5:" %}

      <div class="card article-card ml-3 mt-5" style="width: 20rem;">
        <a href="{% url 'articles:detail' post.post_slug %}">
          <img class="card-img-top" src="{{ post.headline_image.url }}" alt="Card image cap">
        </a>
          <div class="card-body">
            <a href="{% url 'articles:detail' post.post_slug %}">
              <h4 class="card-title">{{ post.title }}</h4>
            </a>
            <p class="card-text">{{ post.short_description }}</p>
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}