FTA/FTA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from datetime import datetime
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
import django.contrib.auth.views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('<sport_slug>/', include('sports.urls')),

    #apis
    path('api/', include('articles.api.urls')),
    path('api/', include('teams.api.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    #path(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FTA/articles/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import IndexView, SportNationView, DetailView
from sports.views import ListView
from django.views.generic import TemplateView

app_name = 'articles'

urlpatterns = [

    path('<slug:sport_slug>/<slug:post_slug>', DetailView.as_view(), name='detail'),
    path('', IndexView.as_view(), name='index'),


    #url(r'^monthly-view/$', cricket.CricketCalendar.as_view(), name='monthly-view'),
    #url(r'^(?P<category_slug>[-_\w]+)/$', sports_views.ListView.as_view(), name='sport-category'),
]

FTA/sports/urls.py
from django.conf.urls import url, include
from django.urls import path
#from sports.api.views import TeamAPIView
from . import views as sports_views
from django.views.generic import TemplateView

from sports.views import SportView, NationView

app_name = 'sports'

urlpatterns = [


    path('<slug:country_slug>/', NationView.as_view(), name='national-home'),
    path('', sports_views.SportView.as_view(), name='sport-home'),
    #url(r'^api_data/', include('sports.api.urls')),
    #url(r'^monthly-view/$', cricket.CricketCalendar.as_view(), name='monthly-view'),
    # path('<slug:country_slug>', sports_views.ListView.as_view(), name='national-home'), #unused
]

FTA/sports/models.py
from django.db import models

# Create your models here.


class Sport_Category(models.Model):
  name = models.CharField(max_length=100, db_index=True)
  category_slug = models.SlugField(max_length=100, db_index=True)

  def __str__(self):
    return self.name

# def get_absolute_url(self):
    # return reverse('sports:sport-category', kwargs={'slug':self.category_slug})


class Sport(models.Model):
  name = models.CharField(max_length=100, db_index=True)
  sport_slug = models.SlugField(max_length=100, db_index=True)
  category = models.ForeignKey('Sport_Category', on_delete=models.CASCADE,)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('sports:national-home', kwargs={'slug': self.sport_slug})

FTA/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}FTA Sport{% endblock %}</title>
      {# Load the tag library #}
      {% load bootstrap4 %}
      {% load static %}
      {% load embed_video_tags %}
      {# Load CSS and JavaScript #}
      {% bootstrap_css %}
      {% bootstrap_javascript %}
      {% bootstrap_jquery %}
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

      {# Display django.contrib.messages as Bootstrap alerts #}
      {% bootstrap_messages %}
      <link rel="stylesheet" href="{% static 'css/main-style.css' %}">
      <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
      <link rel="stylesheet" href="{% static 'font-awesome/font-awesome-4.7.0/css/font-awesome.css' %}">

  </head>
<body>
{% block main_menu %}
{% include "main_menu.html" %}
{% include "sub_menu.html" %}
{% endblock %}

{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}
</body>
</html>

FTA/templates/main_menu.html
{% extends "base.html" %}
{% block main_menu %}
<nav class="navbar navbar-expand-lg main-nav">
  <a class="navbar-brand" href="{% url 'articles:index' %}">FTA Sport</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% for sport_category in categories %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ sport_category.name }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <ul>
            {% for sports in sport_category.sport_set.all %}
              <li><a href="{% url 'sports:sport-home' sports.sport_slug %}">{{ sports.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</nav>
{% endblock %}

FTA/templates/sub_menu.html
{% extends "base.html" %}
{% block main_menu %}
{% if sport_menu.name %}
<div class="container mt-3">
  <nav class="navbar navbar-expand-lg main-nav">
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{get_absolute_url}}">{{sport_menu.name}} |</a>
      </li>
      {% include "submenu/country.html" %}
      {% include "submenu/competition.html" %}
      <li class="nav-item">
        <a class="nav-link" href="">MonthlyView</a>
      </li>
    </ul>
  </div>
  </nav>
</div>
{% else %}
{% endif %}
{% endblock %}